Main files of project
divyanshthinks/First-Capstone pull request #2
Opened 2022-07-02 16:59 UTC by divyanshthinks

This pull request contains the HTML, CSS, and JS files for this capstone project.  It also has all the other files like images and linters.

This is a video that describes what this project does: https://www.loom.com/share/6e9874e586ad4448b8d250564ec3112a

2022-07-02 20:14 UTC, gtekle requested changes
Hi @divyanshthinks :wave: , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/177014956-2baf609d-bc2f-4d32-84ad-9e2057886ba4.gif)

## Highlights
:heavy_check_mark: Nice video presentation
:heavy_check_mark: Home page and about page linked correctly
:heavy_check_mark: Nice hamburger mobile menu button
:heavy_check_mark: Linters setup correctly
:heavy_check_mark: Professional ReadMe

## Suggested changes
_Check the comments under the review._

- [ ] You should deploy the project to `GitHub Pages` or any other deployment platforms such as `Netlify` and provide the live link in the ReadMe and the pull request summary.
![image](https://user-images.githubusercontent.com/44057863/177013206-5c9f96d0-33f3-45fb-a5ee-ab17f8cde963.png)

- [ ] You should all the `<br>` tags that you have used in your two html pages for they adding clutter to your code base and they can be replaced with CSS styling of the block level elements before and after each of them.
- [ ] Kindly adjust the styling of the top social media links and languages bar to align to the design provided. 1) remove the padding(gap) around the bar. 2) add padding on the right side. 3) decrease the size of the icons and the text.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014353-418f4616-d6ce-4100-9de3-f8ce92322830.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014370-3a9d43ef-d2df-4998-9c60-4194a5c45878.png)

- [ ] Kindly adjust the styling of the nav bar to align to the desing. 1) The menu items font-size is smaller in your design as compared to the design. 
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014458-81f00aa2-15fd-4c86-b336-9c3acd7740fc.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014449-d1c27a77-58d3-4d42-b417-bc7ce822fd27.png)

- [ ] The headline section content is left aligned in the design - exactly equal to the logo above but it appears centered on your implementation. Kindly rectify.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014502-628bc859-e75b-4cee-83c6-cc5e8ace743e.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014487-c6cd512c-bdd4-41bf-9134-084b43f39ced.png)

- [ ] You should adjust the styling of the program section according to the design. 1) There is a big padding both on the left and the right sides of the program-items.  2) There is a margin between two program-items. 3) There is border: outline for the mouse hovered program-item. 4) The layout of the contents of a give program-item horizontally centered. 5) the height of each program-item is equal (you may use FlexBox stretch value on either justify-content or align-items properties). 6) the font-size and color seems a little bit different from the design.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014564-71ad33ea-2efc-4ff7-b137-d647554af3d9.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014525-1031a1fe-b9de-41f5-8692-978548fbecaf.png)

- [ ] Kindly adjust the styling of the speakers section to align it look the one in the design.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014676-24309a3a-55a4-498e-8875-588f20eae649.png)
### Impl
![image](https://user-images.githubusercontent.com/44057863/177014662-9c778b23-acbf-4b33-810a-d9a5397fc350.png)

- [ ] Kindly adjust the styling of the footer section to align it to the design
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014726-6d89120a-6c3b-4105-af6a-fc8b0b99cf8c.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014714-10f6ca50-d4ca-492f-a789-5b991f5cb6b2.png)

- [ ] Kindly adjust the styling of the About page headline section to look like the design.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014762-8e4e4079-fb5f-48df-98f4-a274a74a6a02.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014745-91c569ed-352e-4c71-a611-08030c0df7e2.png)

- [ ] Kindly adjust the styling of the previous meetups section as in the design. Add the years on  top of the images, add the shadow color on top of the images make the text accessible, etc
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014805-be871720-bdc3-45bf-bfc8-22f247e5506b.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014812-62893e97-a6ea-4243-873d-46db42989226.png)

- [ ] Kindly center vertically the contents of the Characters section in the mobile version.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014869-731f6480-398c-45e0-baae-4759131c8d9a.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014856-4a137585-5615-47e7-a407-628dd153e7f1.png)

- [ ] As for the desktop version, kindly adjust the layout of the speakers to align to the design.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014893-a5c6e7e5-0dcb-4ea0-8c5e-2cf8a8c23391.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014889-17a2b13e-3544-45ea-920c-b025655f3946.png)

- [ ] The direction of the partners' sections remains horizontal with wrapping allowed - even in the mobile version. Kindly rectify.
#### Design
![image](https://user-images.githubusercontent.com/44057863/177014921-969ea580-0e67-4c6d-8ab7-639548721f03.png)
#### Impl
![image](https://user-images.githubusercontent.com/44057863/177014916-215965aa-ccfc-42c2-b771-836248446927.png)


You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-07-02 20:14 UTC, gtekle commented on README.md
> +
- [ ] You should add a description of what the project is all about. The visitors of your Github profile might like to know what you are trying to develop briefly described.

2022-07-02 20:14 UTC, gtekle commented on README.md
> +# This project is a website built for anime fans.
- [ ] From your home page, I believe, the title of this project is `Anime Fans Meetup` and that is what you need to use as project title here as well.

2022-07-02 20:14 UTC, gtekle commented on README.md
> +
- [ ] Kindly add the live link of your deployed app here.

2022-07-02 20:14 UTC, gtekle commented on README.md
> +
- [ ] You should add the steps one should follow to replicate your project assuming a novice who stumbled at your project would like to replicate it on their local machine.

2022-07-02 20:14 UTC, gtekle commented on README.md
> +- https://www.behance.net/adagio07
- [ ] You should add this content under the `Acknowledgement` section according to the ReadMe [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse. Kindly add the section and put the content under it.
- [ ] You should mention that the original design idea is by Cindy Shin from Behance. For example, 

> Special thanks goes to [Cindy Shin in Behance](https://www.behance.net/adagio07) for the original design idea.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +    <div class="header">
- [ ] Since this is a header section, the most semantically appropriate tag to use is `header`. Kindly rectify.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <div id="top">
- [ ] Since these are lists, it is better to use `<ul>` with `<li>` here for semantic reasons.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <p id="log">Logout</p>
- [ ] These are links and as such you should use `<a>` tag instead of `<p>` and wrap the `<img>` tags in `<a>` tags so that they can be clickable.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <div id="bottom">
- [ ] These are lists and it is semantically more appropriate to use `<ul>` tags here.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <p id="ne">News</p>
- [ ] It is semantically more appropriate to use `<a>` tags for nav links instead of `<p>`. The semantically appropriate place for `<p>` tags is if the content is a paragraph indeed.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <br>
- [ ] Why do we need a `<br>` tag here? Both the `<p>` tag and the `<h1>` tags are block level elements and any space requirement between them can be achieved using CSS `margin` or `padding`.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +            <br>
- [ ] Same here, I don't think we need a `<br>` element here.

2022-07-02 20:14 UTC, gtekle commented on about.html
> +        <div id="featured-animes">
- [ ] This is a section and it is semantically more appropriate to use the `section` tag in this case. What do I mean by semantically appropriate? We the tag that relates or closer in meaning to the content that contains. If it is a list use list, if it is a paragraph use paragraph, if it is a heading use heading tags, if you can use HTML5 semantic tags for sections: article, section, main, header, footer, etc please use those.

2022-07-02 20:14 UTC, gtekle commented on index.html
> +     </ul>
- [ ] I don't think this is a list. If there is a place where you can use the `<div>` tag, it is in places like this where the content is a mixture of several HTML elements. For example, I would have used something like this:
```
<div class="character">
  <img src="">
  <h3 class="character_name"> Character Name </h3>
  <p class="character_description"> Character description </p>
</div>
```

2022-07-02 20:14 UTC, gtekle commented on index.html
> +        </ul>
- [ ] You should not duplicate your HTML code for the sole purpose of styling. Your HTML content should remain the same but it should be styled using CSS media queries for different screen sizes. **NB** This is important!

2022-07-04 13:10 UTC, sinansevgi requested changes
Hi @divyanshthinks , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Great work on the README file. It looks more professional now :+1: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Sinan Sevgi

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-04 13:10 UTC, sinansevgi commented on README.md
> +
:+1: Great work

2022-07-04 13:10 UTC, sinansevgi commented on index.html
> +     <h2 id="sch-h">Anime Characters</h2>
- [ ] Great work on adjusting style, but as you can see in the design template each card should have the same width/height. You can use grid and flexbox to adjust this section.

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +    <div class="header">
- [ ] Looks like you are still using `<div>` tag for the header section, please refactor this tag to `<header>` tag

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +            <div id="top">
- [ ] You have a list of social icons in this section, so it should list in order to be semantically correct. Please refactor this section with corresponding `<ul>` and `<li>` tags

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +            <p id="log">Logout</p>
- [ ] Menu items are expected to be links (whether they are working or not), Please refactor these items to make them listed link items. As suggested by the previous reviewer.

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +            <div id="bottom">
- [ ] You have a list of menu items in this section, so it should list in order to be semantically correct. Please refactor this section with corresponding  `<ul>` and `<li>` tags

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +            <p id="ne">News</p>
- [ ] Menu items are expected to be links (whether they are working or not), Please refactor these items to make them link items. As suggested by the previous reviewer

2022-07-04 13:10 UTC, sinansevgi commented on about.html
> +        <div id="featured-animes">
- [ ] We should always use semantically correct HTML structure. Semantic HTML makes the HTML more comprehensible by better defining the different sections and layout of web pages. Please refactor this `<div>` tag to `<section>` tag

2022-07-04 13:10 UTC, sinansevgi commented on style.css
> +  }
- [ ] Great work on this section, but as you can see in the screenshot shared by the previous reviewer. This section should have some left margin/padding. If you can add a little bit of margin to this section It will look better and be way more readable.

2022-07-04 13:10 UTC, sinansevgi commented on style.css
> +  }
- [ ] Menu item still not following the given design template.
You can make these suggested changes to make the menu look similar:
- Please make the font a little big bigger
- Align menu items to right

[Optional]
- [ ] You can also add [link states](https://htmlandcssguidebook.com/css/link-states/) to make menu items look similar after the link is visited.

2022-07-04 13:10 UTC, sinansevgi commented on style.css
> +#about-cont {
[Optional]
- [ ] You should use class selector instead of id selectors. ID selectors should only be used with unique items we need to access. When using an ID selector, browsers automatically create a javascript variable for the related element and clutters your variable namespace. You should avoid using ID selectors unless you specifically need to use them.

2022-07-04 13:10 UTC, sinansevgi commented on style.css
> +}
- [ ] Great work on making these images vertical in mobile display, but images are not centered as in the design template. You can use margins or text-align to align content

2022-07-04 13:10 UTC, sinansevgi commented on style.css
> +}
- [ ] Content of this section should protect its alignment in the mobile display. You shouldn't convert them to vertical with `flex-direction: column`. Please adjust this section as requested by the previous reviewer

2022-07-05 08:01 UTC, sinansevgi approved these changes
Hi @divyanshthinks , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Program section looks good now :+1: 


Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-05 14:08 UTC, merged